### ISSUE TITLE
Is there lazy loading and thumbnails support?

### ISSUE THREAD

**Issue by eobet** [mvoloskov/fast-image-zoom#11]
Sorry if this seems like either an outdated question (I haven't dabbled in websites in several years) or an out of scope question:

Do I understand it correctly that it's the same image when displayed small, as when zoomed in?

If not, where do you define what image should be loaded when you zoom, and there's no mention of fading/spinner to go between the thumbnail and the zoomed image while it is loading?

**Comment by textpain** [comment]
Hi. Yes, the images are the same. The plugin is just a visual effect that is doesn't bear any functionality by design. This is the only way to keep it config-free.

Lazy loading and displaying a larger version of an image when zoomed is undoubtedly more useful in certain cases, but the amount of “moving parts” in that solution doesn't allow making it config-free in a sensible manner.

**Comment by eobet** [comment]
Thank you for clarifying this!
