### ISSUE TITLE
Slideshow

### ISSUE THREAD

**Issue by pixelcrash** [mvoloskov/fast-image-zoom#12]
Any chance you could make a slideshow out of a set of images with the same .classname - once you are in the light box view?

**Comment by textpain** [comment]
Hi. Appreciate the feedback.

If I'm going to make it, I'm at least going to make it good. A good slideshow lightbox implies good accessibility: It should be a proper modal, it should block the scroll and trap the focus, it should have controls that are readable by a screen-reader and accessible with keyboard, it should announce changing slides. It should contain no other elements than images. So, we should, upon clicking that first image within the list that match the selector, bring all those images into our lightbox container, so we can switch. And on a large enough scroll, we should put them all back, animating the transition of the image we left on going in its place, but if it's too far, perhaps animate it as a fade-out instead of zoom-out.

While that would be an incredible plugin to have, it lays out of the scope of my library.

My plugin is a purely visual effect that implies no function. It's not a library. It goes as far as one can go without crossing the line of bringing the actual functionality. While compromising flexibility, this approach has benefits like not having to have accessibility features (as there are no functional elements to be accessible) and being able to work straight out of the box.

The point of this library is that if you have a website, you can copy and paste a code snippet, and instantly get your images to zoom. That's a low entry barrier I was aiming for.

Slideshow lightbox is not a visual effect. At least we will have to have controls, and that's functionality, with all the accessibility implications we can't avoid. This lays outside the concept of a visual effect.

**Comment by textpain** [comment]
But if you can build the library that does that, it will be amazing, and you can use my transition calculation algorithm and other code without hesitation. I will mention your library in my readme, because developers could use some flexibility and features my plugin can't provide without turning into a library.

**Comment by pixelcrash** [comment]
Thanks for considering it. Totally understandable, this could be opening the pandora box. I am not even close to be able to develop something like that. I love the transition. Something I miss with most lightbox/js. Cargo has a good one here. 
[https://m538.cargo.site/02](https://m538.cargo.site/02)
keep up the good work 

p.s. video would be awesome

**Comment by textpain** [comment]
Video? I think I have a GIF in the readme.

**Comment by textpain** [comment]
I didn't know about Cargo. It looks amazing.

The thing about Cargo is it being a website builder. As developers, they have the ultimate control over how their websites function: the templates, scripts, markup / DOM hierarchy — everything. Opposed to my plugin that is designed to run anywhere and work with any website. This brings its limitations.

**Comment by pixelcrash** [comment]
The Cargo one is really nice - but I understand what you mean.

**Comment by textpain** [comment]
I'm glad you find my transition beautiful :D 
It's cubic-bezier(.25, .8, .25, 1), I found this particular curve to be the most aesthetically pleasing when I was researching transition timing functions.

**Comment by pixelcrash** [comment]
I will write it down :)
