### ISSUE TITLE
caption like medium?

### ISSUE THREAD

**Issue by deadcoder0904** [mvoloskov/fast-image-zoom#7]
this is a great plugin & i would love to see if there's a way to add caption to it?

right below the image, there should be a place where caption is shown using `alt` attribute.

something like `data-caption=true` on `img` to show caption that is the same as `alt` :)

**Comment by textpain** [comment]
Hi again, Akshay! Appreciate the feedback.

The `alt` attribute in images is already accessible to screen-readers and other tools. Caption and `alt`, however, has **entirely different** purposes: `alt` is the **alternative** to what's in the picture, and caption is, well, a caption.

For example, if we have a photo of a historic "stop" sign, `alt` should be "stop", and the caption might be "The stop sign, USA, 1968". They are different. This mix-up is akin to when developers use the `placeholder` attribute instead of `<label>`.

That difference is the reason we have both `alt` and `<figcaption>`. It's important not to confuse people, as they might recognize that `alt` displayed below the image as if it was a caption. Also, with this "feature" introduced, developers might be writing the captions inside `alt` attributes to achieve what they need to use `<figcaption>` for. We shouldn't promote that kind of bad practice.

**Comment by deadcoder0904** [comment]
so how do i achieve the same with `figcaption`? is it a feature of this library or i've to write my own?

i'm using this lib in my blog with `.mdx` file & the `.mdx` component for `Img` looks like:

```tsx
export const Img = ({ className, ...props }: { className: string; props: any }) => (
	// eslint-disable-next-line @next/next/no-img-element, jsx-a11y/alt-text
	<img className={`w-full block mx-auto ${className}`} {...props} />
)
```

now whenever i write `img` in my `mdx` it uses this component. how do i change this to make it show caption? do i need a span?

**Comment by textpain** [comment]
You should use this:
```HTML
<figure>
   <img ... />
   <figcaption>Caption</figcaption>
</figure>
```

In options, you can change the element selector:
```JS
imageZoom({
    selector: `img[alt]:not([alt=""]):not([data-image-zoom-disabled])`,
})
```

Change this selector to represent whatever you're trying to zoom. In this case, it's probably `figure`.

I didn't test the library with elements other than `img`. Though, the code is really simple, just an absolute positioning and some magic with `transform: scale()`.

**Comment by deadcoder0904** [comment]
no i didn't have to use `figure`.

for now, i went with using `alt` as `caption` as it's too much work. here's my component:

```tsx
import { LinkItUrl } from 'react-linkify-it'

export const Img = ({
	className,
	alt,
	caption,
	...props
}: {
	className: string
	alt: string
	caption: string
	props: any
}) => (
	<figure className={`w-full block mx-auto ${className}`}>
		{/* eslint-disable-next-line @next/next/no-img-element, jsx-a11y/alt-text */}
		<img alt={alt} {...props} />
		<figcaption>
			<LinkItUrl>{caption || alt}</LinkItUrl>
		</figcaption>
	</figure>
)
```

and `imageZoom` remains the same:

```tsx
imageZoom()
```

this works fine. thanks again for this wonderful library 🎉
